# Generated by Django 4.2.13 on 2024-06-13 13:59

from django.db import migrations, models
import songs.utility
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('song_file', models.FileField(upload_to=songs.utility.upload_to, validators=[songs.utility.validate_mp3])),
                ('likes', models.IntegerField(default=0)),
                ('metadata', models.JSONField()),
                ('playlist', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
